services:
  - type: web
    name: apparel-inventory-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_DEBUG
        value: "false"
      - key: PORT
        value: "10000"
    autoDeploy: true